server:
    port: 9000
management:
    address: 127.0.0.1
    port: 9100
logging:
    level:
        application: DEBUG
        org.springframework.jdbc.core.JdbcTemplate: DEBUG
spring:
    datasource:
        ###url: jdbc:oracle:thin:ATT_USER/att_user@//192.168.56.101:1521/ORCL
        url: jdbc:oracle:thin:hoshiba/hoshiba123@//192.168.201.162:1521/xe
        driverClassName: oracle.jdbc.driver.OracleDriver
    messages:
        encoding: UTF-8
    thymeleaf:
        cache: false
    session:
        store-type: redis
    redis:
        host: localhost
        password:
        port: 6379
    mvc:
        media-types:
          csv:  text/csv
security:
    user:
        name: manager
        password: ziNYWtS58L8A
    basic:
        enabled: false
line:
    bot:
        lineAtId: '@dza9550o'
        channelToken: GK9qdKrOS1g9nGJky/5B4esbRF0Qk3WEGc2KZVbseK5SR3A/B3/Xww1Zh9SWtGeaD8NTSfrgNo1uJcFwHtLcfCeSNLI2waZxu82D+aJ/Pae1gD6BItcmPnMNdCh63qncoPuLZ9dbBuTBxi1KvKLeiAdB04t89/1O/w1cDnyilFU=
        channelSecret: 1615571d608545ed8cad935d864b5160
    linelogin:
        channelId: 1580090756
        channelSecret: b45effae6c9a9916c16ae48a807753a9
        callbackUrl: https://54.64.5.114:8080/user/auth